version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached
      - firebase-emulators:/home/node/.cache/firebase/emulators/

    command: sudo chown -R node:node /home/node/.cache/firebase && sleep infinity

    user: node

volumes:
  firebase-emulators:
