name: Pr Review

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Format front
        run: yarn prettier -c "services/*/src/**/*.{ts,tsx}"

  front-lint:
    name: Front Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
        working-directory: services/frontend
      - name: Codegen
        run: yarn graphql-codegen
        working-directory: services/frontend
      - name: Lint front
        run: yarn lint
        working-directory: services/frontend

  front-type:
    name: Front Type
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
        working-directory: services/frontend
      - name: Codegen
        run: yarn graphql-codegen
        working-directory: services/frontend
      - name: Type front
        run: yarn tsc --noEmit
        working-directory: services/frontend

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
        working-directory: services/backend
      - name: Codegen
        run: yarn graphql-codegen
        working-directory: services/backend
      - name: Lint backend
        run: yarn lint
        working-directory: services/backend

  backend-type:
    name: Backend Type
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
        working-directory: services/backend
      - name: Codegen
        run: yarn graphql-codegen
        working-directory: services/backend
      - name: Type backend
        run: yarn tsc --noEmit
        working-directory: services/backend
